languages:
    default: 'German',
    fr: 'French',
    en: 'Englisch',
lokalize:
    importkeys: false,
    publicAccess: false,
    delimiter: ";",
    translationService:
        provider: "Google"
        apikey: "AIzaxxx"
