version: "3.7"

services:
  cockpit:
    container_name: cockpit
    image: agentejo/cockpit
    volumes:
      - ./storage:/var/www/html/storage
      - ./config:/var/www/html/config
    ports:
      - 8080:80
